title: titulozada
author: Henrique de Paula
email: tec.henriquedepaula@gmail.com
description: > # testando algumas mudanças nisso aqui se eu não tiver nenhum post aqui

# social links
twitter_username: henrique_exe
github_username: bidwolf
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
