title: Diário de Aprendizado
author: Henrique de Paula Rodrigues
email: tec.henriquedepaula@gmail.com
description: > # Pra cada dia, um aprendizado, pra cada aprendizado, um novo arquivo é postado.
# social links
twitter_username: henrique_exe
github_username: bidwolf
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
