title: Diário de Aprendizado
author: Henrique de Paula Rodrigues
email: tec.henriquedepaula@gmail.com

# social links
twitter_username: henrique_exe
github_username: bidwolf
instagram_username: henrique._.exe
linkedin_username: henriquedepaularodrigues
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
