title: Diário de Aprendizado
author: Henrique de Paula Rodrigues
email: tec.henriquedepaula@gmail.com
description: > # Pra cada dia, um aprendizado, pra cada aprendizado, um novo arquivo é postado.
 Este blog é onde atualizo informações a respeito do
 meu aprendizado no dia em questão, podendo conter conteúdo sobre 
 programação ou não.
# social links
twitter_username: henrique_exe
github_username: bidwolf
instagram_username:henrique._.exe
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
